version: "3.8"
services:
  tapo_exporter:
    hostname: tapo_exporter
    container_name: tapo_exporter
    image: ghcr.io/yukics/tapo-plug-exporter:latest
    # image: yuki/tapo-exporter:latest
    restart: always
    volumes: # Comment on production, DEV purpose
      - ./main.py:/usr/src/app/main.py
      - ./logging.conf:/usr/src/app/logging.conf
      - ./tapo.json:/usr/src/app/tapo.json
    environment:
      - TZ=Europe/Madrid
      - TAPO_USER=correo@mail.com
      - TAPO_PASS=password
      - PROMETHEUS_MULTIPROC_DIR=/tmp
    networks:
      net_monitoring:
    ports:
      - 9120:8000
networks:
  net_monitoring:
    external: true
